server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/java6MovieApp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

